POST http://localhost:5000/create-room
Content-Type: application/json

{
    "title": "2 bed room",
    "price": 100,
    "people": 2,
    "desc": "allow smoking",
    "roomNumbers": 5
}


#######

POST http://localhost:5000/create-hotel
Content-Type: application/json

{
    "name": "Sen Boutique",
    "type": "Appartment",
    "city": "Ho Chi Minh",
    "address": "5 Nguyen Cu, Thao Dien Ward, District 2",
    "distance": "1.5km from center",
    "photos": "aaaaa",
    "desc": "cozy and chill",
    "price": 900000,
    "rating": 5,
    "featured": "Yes"
}

#######

POST http://localhost:5000/client/hotel/search
Content-Type: application/json

{
    "city": "ho chi minh",
    "people": 6,
    "timeRange": "{{$timestamp}}"
}

#######

POST http://localhost:5000/admin/room/create
Content-Type: application/json

{
    "city": "ho chi minh",
    "people": 6,
    "timeRange": "{{$timestamp}}"
}

#######

POST http://localhost:5000/client/transaction/create
Content-Type: application/json

{
  "user": "648f22da8b1b7f20020fb169",
  "hotel": "648f23d48b1b7f20020fb191",
  "rooms": [
    "648f23b38b1b7f20020fb17f",
    "648f23a08b1b7f20020fb177"
  ],
  "roomsNumber": [
    103,
    101
  ],
  "dateStart": "2023-06-17T17:00:00.000Z",
  "dateEnd": "2023-06-18T17:00:00.000Z",
  "price": 200,
  "payment": "Credit Card",
  "status": "Booked"
}